# This is the configuration file for deploying the site to your Netlify

[build]
  base = "./"
  publish = "dist/"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "https://zixinwang.me/"
  status = 301
  force = true
